### ISSUE TITLE
How to generate bozorth3, cwsq and  mindtct?

### ISSUE THREAD

**Issue by aroeiraio** [derickfelix/fcmb#4]
Hello Derick,

I'm trying to use your code, and I'm not being able to generate that three binary files. Of course, they are in the release file, but I would like to understand how do you made these files.

Could you explain?

Thanks

**Comment by thederickff** [comment]
Hello Carlos,
These three applications are some of the NBIS (NIST Biometric Image Software) applications which is available on [this repository](https://github.com/lessandro/nbis).

Sorry for the late response.
