### ISSUE TITLE
Failed to open file C:/registros/bmp/Santiago2.bmp for writing!

### ISSUE THREAD

**Issue by sciapuscio** [derickfelix/fcmb#5]
Hello!!!
You really made my life easier with this! Just a thing when I roll my finger... here the log:

C:\Users\Santiago\Desktop\superFutronic\fcmb-v1.1.2-windows-x86_64\fcmb>fcmb C:/registros/ Santiago2
Please put your finger on the scanner:
Please put your finger on the scanner:
Fingerprint image is written to file: C:/registros/Santiago2.bmp
Failed to open file C:/registros/bmp/Santiago2.bmp for writing!

I opened cmd as Administrator...
What's going on here???

By the other way,
XYT file is generated and I can play matchs with Bozorth3 =D
Rockit!

Thankssss!!!

**Comment by SolomonYakubu** [comment]
Create a folder named "bmp" in the directory, it should solve your problem. That's where the finger print image goes

**Comment by sciapuscio** [comment]
Worked perfectly!

Thanks!

**Comment by SolomonYakubu** [comment]
> Worked perfectly!
> 
> Thanks!

You're welcome
